import { ActivityItem } from "@/admin/components/activity-feed";

export const mockUsers = [
  {
    id: "1",
    name: "Sarah Anderson",
    email: "sarah@techstartup.com",
    business: "Tech Startup Inc.",
    plan: "Pro",
    status: "active",
    joinDate: "2025-12-15",
    avatar: "SA",
  },
  {
    id: "2",
    name: "Michael Chen",
    email: "michael@ecommerce.com",
    business: "E-commerce Solutions",
    plan: "Enterprise",
    status: "active",
    joinDate: "2025-11-20",
    avatar: "MC",
  },
  {
    id: "3",
    name: "Emma Wilson",
    email: "emma@consulting.com",
    business: "Consulting Group",
    plan: "Starter",
    status: "suspended",
    joinDate: "2025-10-05",
    avatar: "EW",
  },
  {
    id: "4",
    name: "David Martinez",
    email: "david@agency.com",
    business: "Creative Agency",
    plan: "Pro",
    status: "active",
    joinDate: "2025-09-30",
    avatar: "DM",
  },
  {
    id: "5",
    name: "Lisa Thompson",
    email: "lisa@retail.com",
    business: "Retail Group",
    plan: "Pro",
    status: "active",
    joinDate: "2025-08-12",
    avatar: "LT",
  },
];

export const mockTransactions = [
  {
    id: "txn_001",
    user: "Sarah Anderson",
    category: "Software",
    amount: 4500,
    type: "debit",
    date: "2026-05-18",
    status: "completed",
  },
  {
    id: "txn_002",
    user: "Michael Chen",
    category: "Inventory",
    amount: 12500,
    type: "debit",
    date: "2026-05-17",
    status: "completed",
  },
  {
    id: "txn_003",
    user: "Emma Wilson",
    category: "Services",
    amount: 8200,
    type: "debit",
    date: "2026-05-17",
    status: "pending",
  },
  {
    id: "txn_004",
    user: "David Martinez",
    category: "Marketing",
    amount: 3600,
    type: "debit",
    date: "2026-05-16",
    status: "completed",
  },
  {
    id: "txn_005",
    user: "Lisa Thompson",
    category: "Operations",
    amount: 15000,
    type: "debit",
    date: "2026-05-16",
    status: "completed",
  },
];

export const mockActivity: ActivityItem[] = [
  {
    id: "act_001",
    type: "signup",
    user: "Sarah Anderson",
    description: "Signed up for Pro plan",
    timestamp: "2 hours ago",
  },
  {
    id: "act_002",
    type: "transaction",
    user: "Michael Chen",
    description: "Processed transaction of $12,500",
    timestamp: "4 hours ago",
  },
  {
    id: "act_003",
    type: "login",
    user: "Emma Wilson",
    description: "Logged in",
    timestamp: "6 hours ago",
  },
  {
    id: "act_004",
    type: "delete",
    user: "Admin",
    description: "Deleted user account (John Doe)",
    timestamp: "1 day ago",
  },
  {
    id: "act_005",
    type: "action",
    user: "David Martinez",
    description: "Updated business profile",
    timestamp: "2 days ago",
  },
];

export const mockFeedback = [
  {
    id: "fb_001",
    user: "Sarah Anderson",
    subject: "Great AI insights!",
    message: "The AI-powered recommendations have saved us hours of work.",
    type: "positive",
    date: "2026-05-17",
    status: "new",
  },
  {
    id: "fb_002",
    user: "Michael Chen",
    subject: "Feature request",
    message: "Would love to see bulk transaction import feature.",
    type: "suggestion",
    date: "2026-05-16",
    status: "reviewed",
  },
  {
    id: "fb_003",
    user: "Emma Wilson",
    subject: "API documentation issue",
    message: "The API docs seem outdated for v2.",
    type: "issue",
    date: "2026-05-15",
    status: "in-progress",
  },
];

export const chartData = {
  userGrowth: [
    { month: "Jan", value: 120 },
    { month: "Feb", value: 190 },
    { month: "Mar", value: 290 },
    { month: "Apr", value: 390 },
    { month: "May", value: 520 },
  ],
  transactionVolume: [
    { month: "Jan", value: 45000 },
    { month: "Feb", value: 62000 },
    { month: "Mar", value: 78000 },
    { month: "Apr", value: 95000 },
    { month: "May", value: 128000 },
  ],
  dailySignups: [
    { day: "Mon", value: 12 },
    { day: "Tue", value: 18 },
    { day: "Wed", value: 14 },
    { day: "Thu", value: 22 },
    { day: "Fri", value: 28 },
    { day: "Sat", value: 8 },
    { day: "Sun", value: 5 },
  ],
};
